title:        chengenbao
tagline:      'I do && I can'
description:  'A good book is the best of friends, the same today and forever.'
url:          http://chengenbao.github.io
version:      1.1.1
author:
  name:       'chengenbao'
  email:      'genbao.chen@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
