title: chengenbao
tagline: 'I do && I can'
description: 'A good book is the best of friends, the same today and forever.'
url: https://chengenbao.github.io
author:
  name: chengenbao
  email: genbao.chen@gmail.com
  github: chengenbao
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/page:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge
