title:        chengenbao
tagline:      'I do && I can'
description:  'Yesterday, I waste my day for the god; Today, is the day for myself!'
url:          http://chengenbao.github.io
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
